In [ ]:
!pip install -U symspellpy

Collecting symspellpy
  Downloading symspellpy-6.7.5-py3-none-any.whl (2.6 MB)
     |████████████████████████████████| 2.6 MB 5.2 MB/s
Collecting editdistpy>=0.1.3
  Downloading editdistpy-0.1.3-cp37-cp37m-manylinux_2_5_x86_64.manylinux1_x86_64.manylinux_2_17_x86_64.manylinux2014_x86_64.whl (125 kB)
     |████████████████████████████████| 125 kB 26.1 MB/s
Installing collected packages: editdistpy, symspellpy
Successfully installed editdistpy-0.1.3 symspellpy-6.7.5

In [1]:
import os
os.chdir('drive/MyDrive/comp4462/MC3')
os.getcwd()

'/content/drive/MyDrive/comp4462/MC3'

In [2]:
#load dataset
import pandas as pd
df_text = pd.read_csv('YInt.csv')
df_text

                      time  ...                                            message
0      2020-04-06 00:00:00  ...  Take advantheeseage of theesehese One, theeser...
1      2020-04-06 00:00:00  ...  @WatchesThomasBird fork it you're back in he s...
2      2020-04-06 00:02:00  ...  Two month left bedoreefore you loose this vibe...
3      2020-04-06 00:04:00  ...                        billeeeeer, i miss ytouou !
4      2020-04-06 00:07:00  ...  You obviously need to use rumble! #rumble #toW...
...                    ...  ...                                                ...
41936  2020-04-10 11:59:00  ...  next were going to watch them take down our ho...
41937  2020-04-10 11:59:00  ...  someone something something On someone he they...
41938  2020-04-10 11:59:00  ...  re: Do yall think i can take my yacht out for ...
41939  2020-04-10 11:59:00  ...  re: guys we have no water and mittens and i ha...
41940  2020-04-10 11:59:00  ...   might as well go try to help at the theater.....

[41941 rows x 4 columns]

In [ ]:
df_text.message = df_text.message.astype(str)

In [ ]:
#remove string start with @
import re
df_text_no_at = df_text
df_text_no_at['message'] = df_text_no_at['message'].str.replace('@(\w+)', '', regex=True)
df_text_no_at

                      time  ...                                            message
0      2020-04-06 00:00:00  ...  Take advantheeseage of theesehese One, theeser...
1      2020-04-06 00:00:00  ...   fork it you're back in he someneomething he s...
2      2020-04-06 00:02:00  ...  Two month left bedoreefore you loose this vibe...
3      2020-04-06 00:04:00  ...                        billeeeeer, i miss ytouou !
4      2020-04-06 00:07:00  ...  You obviously need to use rumble! #rumble #toW...
...                    ...  ...                                                ...
41936  2020-04-10 11:59:00  ...  next were going to watch them take down our ho...
41937  2020-04-10 11:59:00  ...  someone something something On someone he they...
41938  2020-04-10 11:59:00  ...  re: Do yall think i can take my yacht out for ...
41939  2020-04-10 11:59:00  ...  re: guys we have no water and mittens and i ha...
41940  2020-04-10 11:59:00  ...   might as well go try to help at the theater.....

[41941 rows x 4 columns]

In [ ]:
#remove @ name and split hashtag
import re
df_text_hashtag = df_text_no_at
df_text_hashtag['hashtag'] = df_text_hashtag['message'].str.findall('#(\w+)')
df_text_hashtag['message'] = df_text_hashtag['message'].str.replace('#(\w+)','', regex=True)
df_text_hashtag

                      time  ...             hashtag
0      2020-04-06 00:00:00  ...                  []
1      2020-04-06 00:00:00  ...   [MakesItyoureCan]
2      2020-04-06 00:02:00  ...                  []
3      2020-04-06 00:04:00  ...                  []
4      2020-04-06 00:07:00  ...  [rumble, toWonder]
...                    ...  ...                 ...
41936  2020-04-10 11:59:00  ...                  []
41937  2020-04-10 11:59:00  ...                  []
41938  2020-04-10 11:59:00  ...                  []
41939  2020-04-10 11:59:00  ...                  []
41940  2020-04-10 11:59:00  ...                  []

[41941 rows x 5 columns]

In [ ]:
import pkg_resources
from symspellpy import SymSpell

sym_spell = SymSpell(max_dictionary_edit_distance=5, prefix_length=12)
dictionary_path = pkg_resources.resource_filename(
    "symspellpy", "frequency_dictionary_en_82_765.txt"
)
bigram_path = pkg_resources.resource_filename(
    "symspellpy", "frequency_bigramdictionary_en_243_342.txt"
)
# term_index is the column of the term and count_index is the
# column of the term frequency
sym_spell.load_dictionary(dictionary_path, term_index=0, count_index=1)
sym_spell.load_bigram_dictionary(bigram_path, term_index=0, count_index=2)

# lookup suggestions for multi-word input strings (supports compound
# splitting & merging)
input_term = df_text_hashtag['message'][0]
# max edit distance per lookup (per single word, not per whole input string)
suggestions = sym_spell.lookup_compound(input_term, max_edit_distance=5)
# display suggestion term, edit distance, and term frequency
for suggestion in suggestions:
    print(suggestion)

take advantages age of thee these one thees trembling sales, 11, 0

In [ ]:
df_text_hashtag['message'] = df_text_hashtag['message'].map(lambda x: sym_spell.lookup_compound(x, max_edit_distance=5))
df_text_hashtag

                      time  ...             hashtag
0      2020-04-06 00:00:00  ...                  []
1      2020-04-06 00:00:00  ...   [MakesItyoureCan]
2      2020-04-06 00:02:00  ...                  []
3      2020-04-06 00:04:00  ...                  []
4      2020-04-06 00:07:00  ...  [rumble, toWonder]
...                    ...  ...                 ...
41936  2020-04-10 11:59:00  ...                  []
41937  2020-04-10 11:59:00  ...                  []
41938  2020-04-10 11:59:00  ...                  []
41939  2020-04-10 11:59:00  ...                  []
41940  2020-04-10 11:59:00  ...                  []

[41941 rows x 5 columns]

In [ ]:
df_new = df_text_hashtag
df_new['message'] = df_new['message'].str[0]
df_new

                      time  ...             hashtag
0      2020-04-06 00:00:00  ...                  []
1      2020-04-06 00:00:00  ...   [MakesItyoureCan]
2      2020-04-06 00:02:00  ...                  []
3      2020-04-06 00:04:00  ...                  []
4      2020-04-06 00:07:00  ...  [rumble, toWonder]
...                    ...  ...                 ...
41936  2020-04-10 11:59:00  ...                  []
41937  2020-04-10 11:59:00  ...                  []
41938  2020-04-10 11:59:00  ...                  []
41939  2020-04-10 11:59:00  ...                  []
41940  2020-04-10 11:59:00  ...                  []

[41941 rows x 5 columns]

In [ ]:
df_new.to_csv('df_text.csv')

In [3]:
df_read = pd.read_csv('df_text.csv')
df_read

       Unnamed: 0  ...                 hashtag
0               0  ...                      []
1               1  ...     ['MakesItyoureCan']
2               2  ...                      []
3               3  ...                      []
4               4  ...  ['rumble', 'toWonder']
...           ...  ...                     ...
41936       41936  ...                      []
41937       41937  ...                      []
41938       41938  ...                      []
41939       41939  ...                      []
41940       41940  ...                      []

[41941 rows x 6 columns]

In [4]:
df_read.message.astype(str)
df_read

       Unnamed: 0  ...                 hashtag
0               0  ...                      []
1               1  ...     ['MakesItyoureCan']
2               2  ...                      []
3               3  ...                      []
4               4  ...  ['rumble', 'toWonder']
...           ...  ...                     ...
41936       41936  ...                      []
41937       41937  ...                      []
41938       41938  ...                      []
41939       41939  ...                      []
41940       41940  ...                      []

[41941 rows x 6 columns]

In [7]:
df_read.message = df_read.message.str.split(',')

In [10]:
df_read.message = df_read.message.str[0]
df_read

       Unnamed: 0  ...                 hashtag
0               0  ...                      []
1               1  ...     ['MakesItyoureCan']
2               2  ...                      []
3               3  ...                      []
4               4  ...  ['rumble', 'toWonder']
...           ...  ...                     ...
41936       41936  ...                      []
41937       41937  ...                      []
41938       41938  ...                      []
41939       41939  ...                      []
41940       41940  ...                      []

[41941 rows x 6 columns]

In [11]:
df_read.to_csv('df_final.csv')